#Script takes in a GML file, such as the type generated by
#network creation scripts, and runs a community detection
#algorithm, outputting the results as a pickled object

import igraph

print "Reading graph"
G = igraph.read("Network name here")
igraph.summary(G)

#focus on giant component, weakly connected
Gsub = Gsub.clusters(mode="weak").giant()

print "Getting communities"
vc = Gsub.community_infomap()

#freeze the clustering for later use
#this is useful as there is some clustering algorithms
#are non-deterministic
print "Outputting"
import pickle
pickle.dump( vc, open( "Clustering Results.p", "wb" ) )

